apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    app: FE
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: adil
  template:
    metadata:
     name: nginx-pod
     labels:
       pod: adil
    spec:
      containers:
      - name: nginx-con
        image: httpd
