apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: test-rs
 labels:
   app: adil
spec:
 replicas: 2
 selector:
   matchLabels:
     app: nginx-app
 template:
   metadata:
     labels:
       app: nginx-app
   spec:
     containers:
     - name: nginx-container
       image: nginx:latest